[[headers]]
  for = "/photos.json" 
  [headers.values]
    Access-Control-Allow-Origin = "http://127.0.0.1:5500" 

    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=3600" #设置缓存
