[[headers]]
  for = "/photos.json" # 请确保这个路径是 photos.json 在你 Netlify 部署的站点中的实际路径
                       # 例如，如果你的 JSON 在 /data/photos.json，这里就写 "/data/photos.json"
  [headers.values]
    Access-Control-Allow-Origin = "https://your-github-username.github.io" # ***这里非常重要，替换为你的 GitHub Pages 网站的实际域名！***
    # 如果你的 GitHub Pages 使用了自定义域名 (例如 www.yourdomain.com), 请填写那个自定义域名。
    # 如果你未来不确定来源域名，或者数据确实是公开的且不敏感，可以设置为 "*" 来允许所有来源访问，但通常不建议。
    Access-Control-Allow-Methods = "GET, OPTIONS" # 允许的 HTTP 方法
    Access-Control-Allow-Headers = "Content-Type" # 允许的请求头
    Cache-Control = "public, max-age=3600" # 建议设置缓存，单位秒（这里是 1 小时），可以根据需求调整
